# Generated by Django 3.0.2 on 2020-02-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('none', 'none'), ('male', 'male'), ('female', 'female')], default='none', max_length=20),
        ),
    ]
